#!/usr/bin/zsh
# generated by ChatGPT, reviewed and tested by Y99dr451l

STATE="$HOME/.cache/monitor-brightness.json"

MON1=1
MON2=2

mkdir -p "$(dirname "$STATE")"
[ -f "$STATE" ] ||  echo '{"master":70,"offset":0}' > "$STATE"

refresh_waybar() { pkill -RTMIN+8 waybar }
get_master() { jq -r '.master' "$STATE"; }
get_offset() { jq -r '.offset' "$STATE"; }
set_state() {
	jq --argjson master "$1" --argjson offset "$2" '.master=$master | .offset=$offset' "$STATE" > "$STATE.tmp" && mv "$STATE.tmp" "$STATE"
}
clamp() {
	local x="$1"
	if [ "$x" -lt 0 ]; then echo 0
	elif [ "$x" -gt 100 ]; then echo 100
	else echo "$x"
	fi
}
apply_ddc_async() {
	local master="$1"
	local offset="$2"
	(
		exec 9>/tmp/brightness-ddc.lock
		flock -n 9 || exit
		second=$((master + offset))
		master=$(clamp "$master")
		second=$(clamp "$second")
		ddcutil --display "$MON1" setvcp 10 "$master"
		ddcutil --display "$MON2" setvcp 10 "$second"
	) &
}

case "$1" in
	get)
		master=$(get_master)
		offset=$(get_offset)
		second=$((master + offset))
		printf '{"text": "☀ %d%%", "tooltip": "%d%% / %d%% (%+d%%)" }' "$master" "$master" "$second" "$offset"
		;;

	up)
		master=$(( $(get_master) + 5 ))
		offset=$(get_offset)
		master=$(clamp "$master")
		set_state "$master" "$offset"
		refresh_waybar
		apply_ddc_async "$master" "$offset"
		;;

	down)
		master=$(( $(get_master) - 5 ))
		offset=$(get_offset)
		master=$(clamp "$master")
		set_state "$master" "$offset"
		refresh_waybar
		apply_ddc_async "$master" "$offset"
		;;

	offset+)
		master=$(get_master)
		offset=$(( $(get_offset) + 5 ))
		set_state "$master" "$offset"
		refresh_waybar
		apply_ddc_async "$master" "$offset"
		;;

	offset-)
		master=$(get_master)
		offset=$(( $(get_offset) - 5 ))
		set_state "$master" "$offset"
		refresh_waybar
		apply_ddc_async "$master" "$offset"
		;;

	sync)
		# master=$(get_master)
		# offset=$(get_offset)
		# apply_ddc_async "$master" "$offset"
		master=$(ddcutil --display "$MON1" getvcp 10 --brief | awk '{print $4}')
		second=$(ddcutil --display "$MON2" getvcp 10 --brief | awk '{print $4}')
		offset=$((second - master))
		set_state "$master" "$offset"
		refresh_waybar
		;;
esac